const translations = {
  it: {
    titolo_contatti: "Contatti",
    parliamo_codice: "Parliamo di codice.",
    contatti_desc1:
      "Scrivimi per un progetto, una collaborazione o semplicemente per",
    contatti_desc2: "confrontarci su Java, Kotlin e React.",
    intro_desc1:
      "Scrivo software da quando avevo undici anni: conosco le spigot-api e springboot con Java, uso kotlin per le app e adesso sto imparando React.",
    intro_project_button: "Vedi i progetti",
    intro_anni_codice: "anni di codice",
    intro_progetti: "progetti",
    intro_linguaggi: "linguaggi principali",
    titolo_progetti: "Progetti",
    progetti_progetti: "progetti",
    progetti_search: "cerca...",
    progetti_recenti: "recenti",
    progetti_ordina: "ordina",
    progetti_tag_tutti: "Tutti",
    progetti_mostra_altri: "Mostra altri",
    titolo_percorso: "Percorso",
    titolo_competenze: "Competenze",
    competenze_strumenti: "strumenti",
    menu_chi_sono: "Chi sono",
    menu_progetti: "Progetti",
    menu_percorso: "Percorso",
    menu_competenze: "Competenze",
    menu_contatti: "Contatti",
  },
  en: {
    titolo_contatti: "Contact",
    parliamo_codice: "Let's talk code.",
    contatti_desc1:
      "Write to me about a project, a collaboration, or simply to",
    contatti_desc2: "talk about Java, Kotlin, and React.",
    intro_desc1:
      "I’ve been writing software since I was eleven: I have experience with the Spigot API and Spring Boot using Java, I use Kotlin for app development, and I’m currently learning React.",
    intro_project_button: "View projects",
    intro_anni_codice: "years coding",
    intro_progetti: "projects",
    intro_linguaggi: "main languages",
    titolo_progetti: "Projects",
    progetti_progetti: "projects",
    progetti_search: "search...",
    progetti_recenti: "recent",
    progetti_ordina: "sort",
    progetti_tag_tutti: "All",
    progetti_mostra_altri: "Show more",
    titolo_percorso: "Journey",
    titolo_competenze: "Skills",
    competenze_strumenti: "tools",
    menu_chi_sono: "About me",
    menu_progetti: "Projects",
    menu_percorso: "Journey",
    menu_competenze: "Skills",
    menu_contatti: "Contact",
  },
};

export default translations;
